#!/bin/env bash

# Use fd and fzf to select multiple files and pass them to Neovim
selected_files=$(fd -LHat f | fzf -m --bind 'ctrl-s:clear-query' | tr '\n' ' ')

# Check if any files were selected
if [ -n "$selected_files" ]; then
    nvim $selected_files
else
    echo "No files selected. Aborting."
fi
