#!/bin/bash

# Check if both option and URL are provided
if [ -z "$1" ] || [ -z "$2" ]; then
  echo "Usage: ytd [-m|-v] <URL>"
  echo "  -m    Download as music (audio only)"
  echo "  -v    Download as video"
  exit 1
fi

option="$1"
url="$2"

# Check the format option
if [ "$option" = "-m" ]; then
  # Music download
  directory="$HOME/Music"
  yt-dlp -x -f bestaudio \
    --add-metadata \
    --embed-thumbnail \
    --convert-thumb png \
    --ppa "ThumbnailsConvertor+ffmpeg_o:-c:v png -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\"" \
    --external-downloader aria2c \
    --external-downloader-args '-c -j 3 -x 3 -s 3 -k 1M' \
    -o "$directory/%(title)s.%(ext)s" "$url" && mpc update
elif [ "$option" = "-v" ]; then
  # Video download
  directory="$HOME/Videos/YT"
  yt-dlp --embed-thumbnail \
    --write-sub \
    --sub-lang en \
    --convert-subs srt \
    --external-downloader aria2c \
    --external-downloader-args '-c -j 3 -x 3 -s 3 -k 1M' \
    -o "$directory/%(title)s/%(title)s.%(ext)s" "$url"
else
  echo "Error: Please specify either -m (music) or -v (video) option."
  echo "Usage: $0 [-m|-v] <URL>"
  exit 1
fi
